-- Run this entire file in Supabase Dashboard -> SQL Editor.
-- Before using the site, also enable Anonymous Sign-Ins under Authentication -> Providers.

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  date date not null unique,
  student_name text not null check (char_length(trim(student_name)) between 1 and 200),
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text,
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

-- Owners may update only photo metadata, not rename/re-date a booking.
revoke update on public.bookings from authenticated;
grant update (photo_url, photo_path, updated_at) on public.bookings to authenticated;

create policy "Bookings are public to read"
on public.bookings for select using (true);

create policy "Anonymous users can book one valid date"
on public.bookings for insert to authenticated
with check (
  auth.uid() = user_id
  and date between date '2026-08-15' and date '2027-06-04'
  and photo_url is null
  and photo_path is null
);

create policy "Booking owners can attach their photo"
on public.bookings for update to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and date between date '2026-08-12' and date '2027-06-04'
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'senior-photos', 'senior-photos', true, 10485760,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can view senior photos"
on storage.objects for select using (bucket_id = 'senior-photos');

create policy "Booking owners can upload their dated photo"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'senior-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
  and exists (
    select 1 from public.bookings b
    where b.user_id = auth.uid()
      and b.date::text = split_part(storage.filename(name), '.', 1)
  )
);

create policy "Booking owners can replace their photo"
on storage.objects for update to authenticated
using (bucket_id = 'senior-photos' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'senior-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- Intentionally no delete policies and no booking DELETE policy.
